export const LibellesString = {
    "LGF": "Longévité",
    "FERV": "Fertilité vaches",
    "FERG": "Fertilité génisses",
    "IVIA1": "Intervalle Velage IA1",
    "REPRO": "Synthèse fertilité",
    "MACL": "Mammites cliniques",
    "STMA": "Santé mamelle",
    "FNAI": "Facilité naissance",
    "FVEL": "Facilité velage",
    "VNAI": "Vitalité naissance",
    "VVEL": "Vitalité velage",
    "LAIT": "Lait",
    "TP": "TP",
    "TB": "TB",
    "MP": "MP",
    "MG": "MG",
    "MU": '? INEL',
    "INEL": 'INEL',
    "CELL": "Cellules",
    "ISU": "ISU",
    "MO": "Morphologie",
    "AA": "Attache avant",
    "AH": "hauteur attache arrière",
    "AJ": "Angle du jarret",
    "AS": 'Aspect',
    "CC": "Capacité corp.",
    "EA": "Ecart avant",
    "EC": "Etat corporel",
    "HS": "Hauteur au sacrum",
    "IA": "Implantation arrière",
    "IB": "Inclinaison du bassin",
    "IS": "Largeur aux ischions",
    "LO": "Locomotion",
    "LT": "Longueur des trayons",
    "LP": "Largeur de poitrine",
    "MA": "Mamelle",
    "ME": "Membres",
    "MR": "Membres arrière vue arr.",
    "PI": "Angle du pied",
    "PJ": "Dist. Plancher Jarret",
    "PS": "Profondeur sillon",
    "TE": "Tempérament",
    "TR": 'Vitesse de traite',
    "EQ": "Equilibre (femelle)",
    "PC": "Profondeur de corps",
  };


export const constantesLabels = {
    // NF_LAIT: "Nb. filles",
    // LAIT: "Lait",
    // TP: "TP",
    // TB: "TB",
    // MP: "MP",
    // MG: "MG",
    // MU: '? INEL',
    // INEL: 'INEL',

    // NF_MO: "Nb. filles",
    // MO: "Morphologie",
    // MA: "Mamelle",
    // CC: "Capacité corp.",
    // ME: "Membres",

    PS: "Profondeur sillon",
    PJ: "Dist. Plancher Jarret",
    EQ: "Equilibre",
    AA: "Attache avant",
    AH: "hauteur attache arrière",
    EA: "Ecart avant",
    IA: "Implantation arrière",
    LT: "Longueur des trayons",
    HS: "Hauteur au sacrum",
    PC: "Profondeur de corps",
    LP: "Largeur de poitrine",
    AS: 'Aspect',
    EC: "Etat corporel",
    IS: "Largeur aux ischions",
    IB: "Inclinaison du bassin",
    AJ: "Angle du jarret",
    PI: "Angle du pied",
    MR: "Membres arrière vue arr.",
    LO: "Locomotion",
    STMA: "Santé mamelle",
    REPRO: "Synthèse fertilité",
    LGF: "Longévité",
    TR: 'Vitesse de traite',
    TE: "Tempérament",
    CELL: "Cellules",
    MACL: "Mammites cliniques",
    FERV: "Fertilité vaches",
    FERG: "Fertilité génisses",
    IVIA1: "Intervalle Velage IA1",
    FNAI: "Facilité naissance",
    FVEL: "Facilité velage",
    VNAI: "Vitalité naissance",
    VVEL: "Vitalité velage",
    // ISU: "ISU",
  };


  export const constanteRadar = {
    LGF: "Longévité",
    REPRO: "Synthèse fertilité",
    STMA: "Santé mamelle",
    LAIT: "Lait",
    INEL: 'INEL',
    TP: "TP",
    CC: "Capacité corp.",
    MA: "Mamelle",
    ME: "Membres",
    TR: 'Vitesse de traite',
  };